EXE_NAME = rush-02

SOURCE_FILES = functs_0.c \
	       functs_1.c \
	       file_system.c \
	       rush_0.c \
	       rush_1.c \
	       main.c

$(EXE_NAME):
	gcc -Wall -Wextra -Werror -o $@ $(SOURCE_FILES) -I includes

fclean:
	rm -rf $(EXE_NAME)
